// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const dateInfo: string;
export const icon: string;
export const time: string;
export const main: string;
export const h2Title: string;
export const h3Title: string;
export const list: string;
