// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const link: string;
export const externalLink: string;
export const internalLink: string;
export const metaLink: string;
export const copyright: string;
