// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mobilePagination: string;
export const topButton: string;
export const lastButton: string;
export const prevButton: string;
export const nextButton: string;
export const icon: string;
