// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postList: string;
export const postItem: string;
export const postTitle: string;
export const postInfo: string;
export const date: string;
export const post: string;
export const update: string;
export const description: string;
export const series: string;
export const tags: string;
