// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pagination: string;
export const prev: string;
export const next: string;
export const nationLinks: string;
export const items: string;
export const text: string;
export const link: string;
