// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postInfo: string;
export const svg: string;
export const listItem: string;
export const postTitle: string;
export const dateInfo: string;
export const series: string;
export const tags: string;
export const description: string;
