// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const blogPost: string;
export const beforeAndAfter: string;
export const before: string;
export const after: string;
export const title: string;
export const postTitle: string;
