// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const check: string;
export const menuBtn: string;
export const list: string;
export const resultArea: string;
export const inner: string;
