// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const check: string;
export const menuBtn: string;
export const dialog: string;
export const input: string;
export const message: string;
export const inner: string;
export const listItem: string;
export const resultArea: string;
