// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const seriesMain: string;
export const tagsMain: string;
export const seriesList: string;
export const tagList: string;
export const link: string;
