// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const wrapper: string;
export const sunIcon: string;
export const moonIcon: string;
export const rotation: string;
